<#
.SYNOPSIS
  Registers the photo gallery as a Scheduled Task that starts at boot.

.DESCRIPTION
  The zero-download alternative to install-service.ps1: uses the built-in Task
  Scheduler instead of NSSM. It starts the gallery at boot without anyone
  logging in, and restarts it if it exits.

  Trade-offs versus the NSSM service: stopping the task terminates Node rather
  than sending Ctrl+C, so the SIGINT handler in index.ts does not run. SQLite is
  in WAL mode and recovers from that, but the service route is cleaner.

  Logs are the app's own dated files under DataDir\logs; the wrapper .cmd only
  catches what dies before the logger exists.

  Run from an elevated PowerShell prompt.

.EXAMPLE
  .\install-task.ps1 -PhotosRoot 'D:\Photos' -DataDir 'C:\GalleryData'
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$PhotosRoot,

    [string]$DataDir = 'C:\GalleryData',

    [int]$Port = 4000,

    [string]$BindHost = '0.0.0.0',

    [string]$TaskName = 'PhotoGallery',

    # Days of daily log files to keep. 0 keeps them forever.
    [int]$LogRetentionDays = 30,

    # Account to run as. LocalSystem cannot reach UNC paths; pass a real user
    # (you will be prompted for the password) if PhotosRoot is a network share.
    [string]$RunAsUser = 'SYSTEM',

    [switch]$TrustProxy
)

$ErrorActionPreference = 'Stop'

$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = [Security.Principal.WindowsPrincipal]::new($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw 'This script must be run from an elevated (Administrator) PowerShell prompt.'
}

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path

# --- Preflight -------------------------------------------------------------

$node = Get-Command node -ErrorAction SilentlyContinue
if (-not $node) { throw 'node was not found on PATH. Install Node.js 20 or newer first.' }
$nodeExe = $node.Source

# Parse `node -v` in PowerShell rather than passing a -e snippet: quoting inside
# a string handed to a native exe gets mangled on Windows.
$nodeVersion = (& $nodeExe -v) -replace '^v', ''
$nodeMajor = [int]($nodeVersion -split '\.')[0]
if ($nodeMajor -lt 20) { throw "Node.js 20 or newer is required (found $nodeVersion)." }

$serverEntry = Join-Path $RepoRoot 'server\dist\index.js'
if (-not (Test-Path $serverEntry)) {
    throw "$serverEntry not found. Run 'npm ci' and 'npm run build' in $RepoRoot first."
}

if (-not (Test-Path (Join-Path $RepoRoot 'web\dist\index.html'))) {
    Write-Warning 'web\dist\index.html not found - the API will run but no UI will be served. Run "npm run build".'
}

if (-not (Test-Path $PhotosRoot)) { throw "PhotosRoot does not exist: $PhotosRoot" }
$PhotosRoot = (Resolve-Path $PhotosRoot).Path

New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
$DataDir = (Resolve-Path $DataDir).Path

$logDir = Join-Path $DataDir 'logs'
New-Item -ItemType Directory -Force -Path $logDir | Out-Null

# --- Wrapper ---------------------------------------------------------------
# Task Scheduler has no environment or redirection support of its own, so the
# task runs this .cmd, which sets both and then execs node.

$wrapper = Join-Path $DataDir 'run-gallery.cmd'
$trustProxyValue = $TrustProxy.IsPresent.ToString().ToLower()
$logCleanup = if ($LogRetentionDays -gt 0) { 'true' } else { 'false' }
$logDays = if ($LogRetentionDays -gt 0) { $LogRetentionDays } else { 30 }

# LOG_CONSOLE=false because the server writes its own dated files under logs\
# and prunes them itself. The redirect below is what is left over: startup
# failures and native crashes, which never reach the logger. Nothing rotates
# that file, which is exactly why nothing routine is allowed into it.
$wrapperBody = @"
@echo off
rem Generated by deploy\windows\install-task.ps1 - re-run that script to change it.
set "PHOTOS_ROOT=$PhotosRoot"
set "DATA_DIR=$DataDir"
set "PORT=$Port"
set "HOST=$BindHost"
set "NODE_ENV=production"
set "TRUST_PROXY=$trustProxyValue"
set "LOG_CONSOLE=false"
set "LOG_CLEANUP=$logCleanup"
set "LOG_RETENTION_DAYS=$logDays"
cd /d "$(Join-Path $RepoRoot 'server')"
"$nodeExe" dist\index.js >> "$logDir\gallery.out.log" 2>&1
"@

Set-Content -Path $wrapper -Value $wrapperBody -Encoding ascii

# --- Register --------------------------------------------------------------

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Write-Host "Task '$TaskName' already exists - replacing it." -ForegroundColor Yellow
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$action  = New-ScheduledTaskAction -Execute $wrapper
$trigger = New-ScheduledTaskTrigger -AtStartup

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -DontStopOnIdleEnd `
    -StartWhenAvailable `
    -RestartCount 999 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -MultipleInstances IgnoreNew

if ($RunAsUser -eq 'SYSTEM') {
    if ($PhotosRoot.StartsWith('\\')) {
        Write-Warning @'
PhotosRoot is a UNC path but the task will run as SYSTEM, which has no access to
network shares. Re-run with -RunAsUser 'DOMAIN\user' so it can read the share.

Performance note: indexing and thumbnailing over SMB is far slower than local
disk. Running the gallery on the machine that holds the photos is faster.
'@
    }
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
        -Settings $settings -User 'SYSTEM' -RunLevel Highest `
        -Description 'Self-hosted photo gallery (Fastify + SQLite).' | Out-Null
} else {
    $cred = Get-Credential -UserName $RunAsUser -Message "Password for $RunAsUser (used to run the gallery task)"
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
        -Settings $settings -User $cred.UserName `
        -Password $cred.GetNetworkCredential().Password -RunLevel Highest `
        -Description 'Self-hosted photo gallery (Fastify + SQLite).' | Out-Null
}

Start-ScheduledTask -TaskName $TaskName
Start-Sleep -Seconds 3

$info = Get-ScheduledTask -TaskName $TaskName | Get-ScheduledTaskInfo

Write-Host ''
Write-Host "Task '$TaskName' registered and started (last result: $($info.LastTaskResult))." -ForegroundColor Green
Write-Host "  URL         http://localhost:$Port"
Write-Host "  Photos      $PhotosRoot"
Write-Host "  Data        $DataDir"
$retention = if ($LogRetentionDays -gt 0) { "kept $LogRetentionDays days" } else { 'kept forever' }
Write-Host "  Logs        $logDir\gallery-<date>.log (one per day, $retention)"
Write-Host "  Startup     $logDir\gallery.out.log (only what dies before the logger)"
Write-Host ''
Write-Host "On the very first run the admin access code is printed to today's log."
Write-Host "  Get-Content '$logDir\gallery-$(Get-Date -Format 'yyyy-MM-dd').log' -Tail 40"
